config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  resources :sessions
  resources :users
  resources :favorites
  resources :pictures do
    collection do
      post :confirm
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at:"/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture

  validates :user_id,{presence: true}
  validates :picture_id,{presence: true}
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :image,presence: true
  validates :content,presence: true,length: {maximum: 140}

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures,through: :favorites,source: :picture

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_validation { email.downcase! }
  has_secure_password
  validates :password,presence: true,length: { minimum:6 }

  mount_uploader :icon, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @user = current_user
    @favorites = @user.favorites.all
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのPictureをいいねしました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのPictureをいいねから外しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.all.order(created_at: :desc)
  end

  def show
    @picture = Picture.find_by(id: params[:id])
    @user = User.find_by(id: @picture.user_id)
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  # GET /pictures/new
  def new
    if params[:back]
      @picture = Picture.new(picture_params)
      if params[:cache][:image] != ""
        @picture.image.retrieve_from_cache! params[:cache][:image]
      end
    else
      @picture = Picture.new
    end
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    @picture.image.retrieve_from_cache! params[:cache][:image]
    if @picture.save
       PictureMailer.picture_mail(@picture).deliver
       redirect_to pictures_path, notice:"投稿しました"
    else
       render "new"
    end
  end

  # PATCH/PUT /pictures/1
  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: 'Picture was successfully updated.'
    else
      render 'edit'
    end
  end

  # DELETE /pictures/1
  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: 'Picture was successfully destroyed.'
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end

  private
  def picture_params
    params.require(:picture).permit(:image,:image_cache,:content)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = '＞ログインに失敗しました'
      render 'index'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = '＞ログアウトしました'
    redirect_to sessions_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to sessions_path(@user.id)
      flash[:notice] = '＞登録完了、ログインできます'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation,:icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1>Favorites Pictures</h1>
<div class="flex-container">
  <% @favorites.each do |fav| %>
    <div>
      <% post = User.find(fav.picture.user_id)%>
      <div class="post-user">
        <span class="post-icon">
          <%= image_tag post.icon %>
        </span>
        <p class="post-name">
          <%= post.name %>
        </p>
      </div>
      <div class="post-picture">
        <%= image_tag (fav.picture.image) %>
      </div>
      <div class="post-menu">
        <%= link_to favorite_path(fav.id), method: :delete do %>
          <i class="fas fa-heart"></i>
        <% end %>
      </div>
      <div class="post-content">
        <%= fav.picture.content %>
      </div>
      <div class="post-time">
        <%= post.created_at.strftime('%Y.%m.%d %H:%M')%>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  </head>

  <body>
    <% if logged_in? %>
      <div id="wrapper">
        <div id= "hwrapper">
          <header>
            <li>
              <%= link_to pictures_path do %>
                <i class="fas fa-home fa-2x"></i>
              <% end %>
            </li>
            <li>
              <%= link_to new_picture_path do %>
                <i class="far fa-plus-square fa-2x"></i>
              <% end %>
            </li>
            <li>
              <%= link_to favorites_path do %>
                <i class="fas fa-heart fa-2x"></i>
              <% end %>
            </li>
            <li>
              <%= link_to user_path(current_user.id) do %>
                <i class="far fa-user fa-2x"></i>
              <% end %>
            </li>
            <li>
              <%= link_to session_path(current_user.id), method: :delete do %>
                <i class="fas fa-sign-out-alt fa-2x"></i>
              <% end %>
            </li>
          </header>
        </div>
      <% end %>
      <div class="container">
        <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
        <%= yield %>
      </div>
      <div id="fwrapper">
        <footer>
          <p>*+:｡.｡create_by_remixk13｡.｡:+*</p>
          <p>It becomes portfolio. Thank you for viewing！</p>
        </footer>
      </div>
      </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture,local: true,url: choose_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
        <p><%= @picture.errors.count %>件のエラー</p>
        <ul>
          <% @picture.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :picture_image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/pictures/confirm.html.erb
<h3>投稿確認</h3>
<%= form_with(model: @picture,url: pictures_path,local: true) do |form| %>
  <div class="flex-container">
    <%= form.hidden_field :content %>
    <div class="post-picture">
      <%= image_tag(@picture.image) %>
      <%= hidden_field_tag :"cache[image]",@picture.image.cache_name %>
    </div>
    <p class="post-content">
      <%= @picture.content %>
    </p>
    <%= form.submit "投稿する" %>
  </div>
<% end %>

<%= form_with(model: @picture,url: new_picture_path,local: true,method: 'get') do |form|%>
  <%= hidden_field :"cache[image]",@picture.image.cache_name %>
  <%= form.hidden_field :content %>
  <%= form.submit '戻る',name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>
<div class="form-menu">
  <%= link_to @picture do %>
    <i class="far fa-eye">内容を見る</i>
  <% end %>
</div>

app/views/pictures/index.html.erb
<h1>All Pictures</h1>
<div class="flex-container">
  <% @pictures.each do |picture| %>
    <div>
      <div class="post-user">
        <span class="post-icon">
          <%= image_tag picture.user.icon %>
        </span>
        <p class="post-name">
          <%= picture.user.name %>
        </p>
      </div>
      <div class="post-picture">
        <%= image_tag picture.image %>
      </div>
      <div class="post-menu">
        <%= link_to picture_path(picture.id) do %>
          <i class="far fa-eye"></i>
        <% end %>
        <% if picture.user_id == current_user.id %>
          <%= link_to edit_picture_path(picture.id),data: {confirm: '本当に編集しますか？'} do %>
            <i class="far fa-edit"></i>
          <% end %>
          <%= link_to picture_path(picture.id),method: :delete, data: { confirm: '本当に削除しますか？' } do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
      <div class="post-content text-truncate">
        <%= picture.content %>
      </div>
      <div class="post-time">
        <%= time_ago_in_words(picture.created_at) %>
      </div>
    </div>
  <% end %>
</div>

app/views/pictures/new.html.erb
<h1>投稿する</h1>

<%= render 'form', picture: @picture %>

app/views/pictures/show.html.erb
<div class="flex-container">
  <div class="post-user">
    <span class="post-icon">
      <%= image_tag @picture.user.icon %>
    </span>
    <p class="post-name">
      <%= @user.name %>
    </p>
  </div>
  <div class="post-picture">
    <%= image_tag(@picture.image_url) if @picture.image.present? %>
  </div>
  <div class="post-menu">
    <% unless @picture.user_id == current_user.id %>
      <% if @favorite.present? %>
        <%= link_to favorite_path(id: @favorite.id), method: :delete do %>
          <i class="fas fa-heart"></i>
        <% end %>
      <% else %>
        <%= link_to favorites_path(picture_id: @picture.id), method: :post do %>
          <i class="far fa-heart">いいね!</i>
        <% end %>
      <% end %>
    <% end %>

    <% if @picture.user_id == current_user.id %>
      <%= link_to edit_picture_path(@picture.id),data: {confirm: '本当に編集しますか？'} do %>
        <i class="far fa-edit"></i>
      <% end %>
    <% end %>
  </div>
  <div class="post-content">
    <%= @picture.content %>
  </div>
  <div class="post-time">
    <%= @picture.created_at.strftime('%Y.%m.%d %H:%M')%>
  </div>
</div>

app/views/users/new.html.erb
<body style="background: linear-gradient(-135deg, #E4A972, #9941D8);">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <% @user.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </div>
  <% end %>
  <div class="user-form">
    <div class="logo">
      新規登録
    </div>
    <div class="form-group">
      <%= form_with(model: @user, local: true) do |f| %>
        <ul>
          <li>プロフィール画像<%= f.file_field :icon,id: :user_icon,class: 'form-control' %></li>
          <li><%= f.hidden_field :icon_cache %></li>
          <li><%= f.text_field :name,class: 'form-control',placeholder: "ユーザーネーム" %><li>
          <li><%= f.email_field :email,class: 'form-control',placeholder: "メールアドレス"%></li>
          <li><%= f.password_field :password,class: 'form-control',placeholder: "パスワード" %></li>
          <li><%= f.password_field :password_confirmation,class: 'form-control',placeholder: "パスワード再入力" %></li>

          <li><%= f.submit "アカウント登録",class: 'btn btn-primary btn-block btn-sm' %></li>
        </ul>
      <% end %>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<h1>User Acount</h1>
<div class="user-prof">
  <div class="user-icon">
    <%= image_tag @user.icon %>
  </div>
  <div class="user-name">
    <%= @user.name %>
  </div>
</div>

<div class="user-mail">
  メールアドレス: <%= @user.email %>
</div>
<div class="user-menu">
  <%= link_to session_path(current_user.id), method: :delete do %>
    <i class="fas fa-sign-out-alt fa-2x">logout</i>
  <% end %>
</div>